### ISSUE TITLE
Display of some reaction rates results in KineticsData error

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-website#123]
looking up the kinetics of butoxyl isomerization CCCC[O] to [CH2]CCCO results in an error from rendering the template from render_kinetics.py in get_rate_coefficients. Seems that somehow the reaction rate parameters are not being used for some data. 

The reaction runs properly using the `generate reactions.ipynb`, so I think this is mostly a website error.

URL generating error: http://rmg.mit.edu/database/kinetics/reaction/reactant1=multiplicity%25202%250A1%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B3%252CS%257D%2520%257B5%252CS%257D%2520%257B6%252CS%257D%250A2%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B4%252CS%257D%2520%257B7%252CS%257D%2520%257B8%252CS%257D%250A3%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B10%252CS%257D%2520%257B11%252CS%257D%2520%257B12%252CS%257D%250A4%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B9%252CS%257D%2520%257B13%252CS%257D%2520%257B14%252CS%257D%250A5%2520%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A6%2520%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A7%2520%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A8%2520%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A9%2520%2520O%2520u1%2520p2%2520c0%2520%257B4%252CS%257D%250A10%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A11%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A12%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A13%2520H%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%250A14%2520H%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%250A__product1=multiplicity%25202%250A1%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B3%252CS%257D%2520%257B6%252CS%257D%2520%257B7%252CS%257D%250A2%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B4%252CS%257D%2520%257B8%252CS%257D%2520%257B9%252CS%257D%250A3%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B5%252CS%257D%2520%257B10%252CS%257D%2520%257B11%252CS%257D%250A4%2520%2520C%2520u1%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B12%252CS%257D%2520%257B13%252CS%257D%250A5%2520%2520O%2520u0%2520p2%2520c0%2520%257B3%252CS%257D%2520%257B14%252CS%257D%250A6%2520%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A7%2520%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A8%2520%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A9%2520%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A10%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A11%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A12%2520H%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%250A13%2520H%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%250A14%2520H%2520u0%2520p0%2520c0%2520%257B5%252CS%257D%250A

**Comment by mliu49** [comment]
I think the issue is that the kinetics entry lists both Tmin and Tmax as 298. The website attempts to fit Arrhenius parameters to the rate data, but is unable to in this case since there is effectively only one data point. I assume that generateReactions works because it does not refit the data? I'm not exactly sure why the website needs to though.

The problematic reaction is reaction 25 in `intra_H_migration/NIST`. The rate is originally from this paper: http://pubs.rsc.org/en/content/articlehtml/2003/cp/b307708j. The paper says that the rates were calculated using DFT at 298 K, but does not explicitly say the range for which the rates are valid.

The solution would be to either modify the temperature range of the database entry or figure out why the website needs to refit data and add a way to handle reactions without a temperature range.

**Comment by mliu49** [comment]
Actually, it wouldn't be too difficult to add a case for Tmin=Tmax where we currently check for the temperature range:
```
if kinetics.Tmin is not None and kinetics.Tmax is not None:
    Tmin = kinetics.Tmin.value_si
    Tmax = kinetics.Tmax.value_si
else:
    Tmin = 300
    Tmax = 2000
```
Maybe we could set a range of 10 K around the temperature if Tmin=Tmax?
