### ISSUE TITLE
"transport properties" fails for some nitrogen species

### ISSUE THREAD

**Issue by cfgoldsmith** [ReactionMechanismGenerator/RMG-website#132]
The website seems unable to provide transport properties for many (most? all?) nitrogen containing species. For example, a search of nitrosomethane, nitromethane, methyl nitrite, and methyl nitrate all return errors of the form:
(for nitrosomethane, ch3no).
```
KeyError at /database/transport/molecule/1 C u0 p0 c0 {2,S} {4,S} {5,S} {6,S} 2 N u0 p1 c0 {1,S} {3,D} 3 O u0 p2 c0 {2,D} 4 H u0 p0 c0 {1,S} 5 H u0 p0 c0 {1,S} 6 H u0 p0 c0 {1,S}

'Node <Entry index=0 label="R"> has no parent with data in the transport database.'

Request Method: 	GET
Request URL: 	http://rmg.mit.edu/database/transport/molecule/1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B4,S%7D%20%7B5,S%7D%20%7B6,S%7D%0A2%20N%20u0%20p1%20c0%20%7B1,S%7D%20%7B3,D%7D%0A3%20O%20u0%20p2%20c0%20%7B2,D%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A5%20H%20u0%20p0%20c0%20%7B1,S%7D%0A6%20H%20u0%20p0%20c0%20%7B1,S%7D%0A
Django Version: 	1.8.4
Exception Type: 	KeyError
Exception Value: 	

'Node <Entry index=0 label="R"> has no parent with data in the transport database.'

Exception Location: 	/var/www/RMG-Py/rmgpy/data/transport.py in __addCriticalPointContribution, line 527
```
It does, however, find the correct thermo for each species (e.g. thermo_DFT_CCSDTF12_BAC).

**Comment by mliu49** [comment]
I think the issue is just lack of data. We have very few [group entries](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/transport/groups/ring.py) in the transport database, with none at all for nitrogen.

Although, it would be better if the website could handle this error and give a more user-friendly message.

**Comment by mliu49** [comment]
The website has just been updated so that it will use the fallback method (fixed Lennard-Jones parameters) to estimate transport properties when it cannot match any groups. I think we still lack Joback groups for nitrogen, so nitrogen species will always use fixed parameters unless they are in a library.

The website will now at least give numbers for every species, although they are not necessarily good numbers.
