### ISSUE TITLE
Many searches for Transport Properties give server error

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-website#150]
The server error page no longer gives clues to help debug.

Searches for `[O]`, `[OH]`, `water`, `methane` are all giving errors.
Some things (like `O2`) currently work.

**Comment by mliu49** [comment]
This has been an issue for a long time, but I haven't looked into it. Issue #132 reports the same error. Basically, any molecule which hits the top node in the tree will fail due to not having data.

After looking into it more just now, it's actually a really simple fix. A while ago, another way to estimate transport was added for cases where group additivity failed (ReactionMechanismGenerator/RMG-Py@32cb9301a357890b07153f37e835392bf6be79b0), but the method used for transport search (`getAllTransportProperties`) was not changed. See [PR #994](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/994) in RMG-Py.

**Comment by rwest** [comment]
thanks for looking at (and fixing) this so quickly

**Comment by mliu49** [comment]
The live website has just been updated. This issue should be fixed.
