### ISSUE TITLE
InChI species identifier seems broken in Molecule Search

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-website#151]
I get the following error when typing any InChi in Molecule Search:
```
Not Found
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
```
(also when clicking the InChI JavaScript that generates an example from the header)

**Comment by mliu49** [comment]
Thanks for reporting this. For some reason, it works on localhost. I'll look more into it when I get a chance.

**Comment by mliu49** [comment]
For some reason, Django can't resolve the URL. For the example link, the site tries to get the adjlist from `http://rmg.mit.edu/adjacencylist/InChI%3D1S%2FC7H8O%2Fc8-6-7-4-2-1-3-5-7%2Fh1-5%2C8H%2C6H2`, but instead receives a 404 error. My guess it that it has to do with the slashes in the InChI, but it's odd since they should encoded properly.

I cannot reproduce this at all using the local development server, so I'm not sure how to proceed. The only option might be to try debugging on the (dev) production server.

**Comment by mliu49** [comment]
Changes have been pushed to the live website. InChI works now.
