### ISSUE TITLE
What are those S(#) species doing in my RMG model?

### ISSUE THREAD

**Issue by shrabanti1937** [ReactionMechanismGenerator/RMG-website#167]
Hi 
I am trying generate a details mechanism of methane at (298-2600)K temperature range , (1-40)bar pressure and varying equivalence ratio. I also wanted the nox to be present in my mechanism. I use the termination with time. While doing so I found after some time the mechanism starts generating same species again and again with different string number along with few new species. eg: it generated following Sulfurs. S(610)  S(1059)     S(1060)  S(3840)     S(4695) . I was wondering why its happening and how to handle this.

**Comment by shrabanti1937** [comment]
Thanks @alongd . I did't realize that. Thats really helpful.
However, if now I want to use the generated mechanism suppose to calculate laminar flame speed using chemkin or cantera, how can I convert those species name to there real name?

**Comment by alongd** [comment]
You could use the Replace function of your text editor to replace `S(1322)` with the species name of your choice.
Some points to consider:
- make sure to manually fix the thermo section of the Chemkin file (those 1,2,3,4 at the end of each thermo entry must be aligned at a certain location, otherwise Chemkin complaints)
- you need to come up with a new name which isn't too long (less that 15 chars should be good)
- make sure the new species name are unique and don't contain spacial characters
- you don't have to rename all `S(#)` species... - not all are important for your analysis

**Comment by alongd** [comment]
You don't have to replace the species names, unless you really want to. You can run your flame speed or other calculations, and when you plot the results (Excel, Python, etc.), just note which species is which.
If you'd still like to replace the names in the Chemkin file, you can replace it with the formula you found or any other name that makes sense to you, as long as it is unique (don't define two species with the same name).
You're asking how to tell which species are important - but how do you define "importance"? If you mean species a certain observable is sensitive to its thermo or to a reaction it participates in, then run a sensitivity analysis. If you mean species which have a high flux, then run a rate of production analysis (Chemkin/Cantera will do both).
I'll also note that while these basic questions are important for anyone generating mechanisms, this specific page isn't the place to discuss them since it is outside the scope of the current issue, and in addition this is the RMG-website GitHub pages (perhaps it would be more appropriate to open similar issue and raise questions in the [RMG-Py GutHub pages](https://github.com/ReactionMechanismGenerator/RMG-Py), where future users are more likely to search for answers for such questions). Please don't see the last comment as a discouragement to ask questions, they are most welcome, but just let's continue the discussion in a place where it is easy to find in the future.
