### ISSUE TITLE
Error in "Convert Chemkin File"

### ISSUE THREAD

**Issue by jimchu10** [ReactionMechanismGenerator/RMG-website#177]
For new RMG mechanisms, some new comments are included, but they cannot be processed well in "Convert Chemkin File".

For example:
! BM rule fitted to 2 training reactions at node Root_1R->H_N-2R-inRing_N-2R->H_N-2CNOS->S_2CNO->C_Ext-2C-R_N-Sp-3R!H=2C_Ext-2C-R_Ext-2C-R
!     Total Standard Deviation in ln(k): 0.0104217745851

**Comment by xiaoruiDong** [comment]
Thanks Jim for reporting the bug. I will take a look soon.

**Comment by mliu49** [comment]
I think this is simply because the RMG version that the website is using is not fully up to date.

**Comment by xiaoruiDong** [comment]
The RMG-website' backend version is v2.4.1 (the latest release version before converting to py3). There are some updates afterward which are not supported by the website. I checked RMG master branch and it is not clear which commit I should update to (Probably to the commits on Aug 10, 2019, but I do see furturize commit before that). At this point, I think it may be better to start to futurize the website instead of updating the website's backend RMG.

**Comment by xiaoruiDong** [comment]
@Jimchu, if you are still interested, can you try the same job again with the newest RMG website? Thanks!
