### ISSUE TITLE
Kinetics Estimator unable to recognize NOx disproportionation (missing class?)

### ISSUE THREAD

**Issue by mefuller** [ReactionMechanismGenerator/RMG-website#198]
I provided explicit reactants and products for a disproportionation:
CCCCCO[O] + [N]=O <=> CCCCC[O] + [O]N=O

The kinetics estimator returns only:
> Kinetics Search Results
> No results found.
> 
> Our database could not find any reactions between these two species which give new products. If you think this is an error, please post an issue on our GitHub page.

Is there a missing reaction class?

**Comment by alongd** [comment]
I _think_ (please check) that the actual reaction might be pressure dependent:
CCCCCO[O] + [N]=O <=> CCCCCOON=O* <=> CCCCC[O] + [O]N=O
This section of the website only discovers elementary paths.
Try to see what an actual RMG job says about this reaction (allowing PDep).

**Comment by mefuller** [comment]
I have run calculations (PAPR/MESS) on n-propyl (versus n-pentyl) and also for methyl and ethyl and the result is interesting:
I modelled the system as pressure-dependent but the well is skipped at all combustion-relevant temperatures (input range 400 to 2500 K and only at 30+ atm is the well persisting to perhaps 450 K). The RO[O] + [N]=O <=> R[O] + [O]N=O rates as calculated are constant over the range of 400 to 2500 K and pressures of 0.01 to 100 atm, so perhaps this should be treated as an elementary disproportionation class since well-skipping occurs at all conditions of interest.

**Comment by alongd** [comment]
I think that, fundamentally, an "oxygen abstraction" reaction is not elementary. I'm unsure how or whether this disproportionation is different (it could very well be). Since I'm uncertain, I can ask leading questions, hopefully they are helpful. For example, will the reaction pass through a `CCCCCOON=O` isomer at extremely low temperatures (if one is interested in atmospheric or interstellar chemistry)? Another aspect is that this reaction channel could be roaming through this isomer, and even if it does not being quenched into this isomer, it does pass through it. To always skip the isomer in model generation and declare this an elementary family, we need to be certain that no reaction in this new family requires this isomer for their description. Perhaps the observation that you mentioned should be the outcome of a PDep calculation?

**Comment by mefuller** [comment]
You're absolutely correct that the reaction likely proceeds through the unimolecular well at extremely low temperatures and pressures.
I suppose the best thing is to work my results into training / database information for RMG so that we can accurately describe these processes and not subsume it into a purely elementary process. The high-pressure limit is extremely low, but it's better to get this right.
Closing this issue and we can discuss offline /elsewhere about how best to work on this problem.

**Comment by alongd** [comment]
This is a good point, and something I don't know if at all possible: adding training reactions for PDep paths.
I think we could add this rate to a specific library (e.g., [PrimariNitrogen](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/kinetics/libraries/primaryNitrogenLibrary/reactions.py)). Happy to talk offline.
