### ISSUE TITLE
Searching for "carbon monoxide" yields formaldehyde

### ISSUE THREAD

**Issue by cgrambow** [ReactionMechanismGenerator/RMG-website#257]
### Bug Description
Searching for "carbon monoxide" on the RMG website yields formaldehyde.

### How To Reproduce
Go [here](http://rmg.mit.edu/molecule_search) and type "carbon monoxide".

### Expected Behavior
I would expect the search to return the correct adjacency list for carbon monoxide. Presumably "carbon monoxide" is translated to `C=O` in SMILES format, which is formaldehyde.

**Comment by JacksonBurns** [comment]
@jonwzheng can you take a look at this, and try and reproduce it on current RMG-website?

**Comment by jonwzheng** [comment]
Looks like this issue was fixed in #194.  Marking as resolved!

**Comment by jonwzheng** [comment]
The issue is indeed that the NCI CIR returns the wrong structure for formaldehyde.  I believe that the root cause is actually from OPSIN, which the CIR mainly relies on for name translation (in addition to pulling from some databases).
To reproduce this, if you search for `carbon monoxide` in OPSIN, it will return `[C]=O`. Possibly this string is then erroneously sanitized to `C=O` and misinterpreted as formaldehyde.

**Comment by JacksonBurns** [comment]
@jonwzheng have you considered filing a bug report to [NCI](https://cactus.nci.nih.gov/ncicadd/contact.html)?
